syntax = "proto3";

package streamfusion.plan.v1;

option java_multiple_files = true;
option java_package = "tech.streamfusion.proto.plan.v1";

message NativePlan {
  uint32 protocol_version = 1;
  Operator root = 2;
}

message Operator {
  oneof operator {
    Input input = 1;
    Calc calc = 2;
  }
}

message Input {
  Schema schema = 1;
}

message Calc {
  Operator input = 1;
  repeated Expression projections = 2;
  optional Expression condition = 3;
}

message Expression {
  oneof expression {
    InputReference input_reference = 1;
    IntegerLiteral integer_literal = 2;
    GreaterThanOrEqual greater_than_or_equal = 3;
    Comparison comparison = 4;
    Arithmetic arithmetic = 5;
    NullCheck null_check = 6;
    BooleanBinary boolean_binary = 7;
    BooleanNot boolean_not = 8;
    LongLiteral long_literal = 9;
    ByteLiteral byte_literal = 10;
    ShortLiteral short_literal = 11;
    FloatLiteral float_literal = 12;
    DoubleLiteral double_literal = 13;
    DateLiteral date_literal = 14;
    TimeLiteral time_literal = 15;
    TimestampLiteral timestamp_literal = 16;
    DecimalLiteral decimal_literal = 17;
    BooleanLiteral boolean_literal = 18;
    StringLiteral string_literal = 19;
    BinaryLiteral binary_literal = 20;
    UnaryMinus unary_minus = 21;
  }
}

message IntegerLiteral {
  int32 value = 1;
}

message LongLiteral {
  int64 value = 1;
}

message ByteLiteral {
  int32 value = 1;
}

message ShortLiteral {
  int32 value = 1;
}

message FloatLiteral {
  float value = 1;
}

message DoubleLiteral {
  double value = 1;
}

message DateLiteral {
  int32 epoch_day = 1;
}

message TimeLiteral {
  int32 millisecond_of_day = 1;
  uint32 precision = 2;
}

message TimestampLiteral {
  int64 epoch_millisecond = 1;
  int32 nano_of_millisecond = 2;
  uint32 precision = 3;
}

message DecimalLiteral {
  string unscaled_value = 1;
  uint32 precision = 2;
  int32 scale = 3;
}

message BooleanLiteral {
  bool value = 1;
}

message StringLiteral {
  string value = 1;
}

message BinaryLiteral {
  bytes value = 1;
  bool fixed_width = 2;
  uint32 length = 3;
}

message UnaryMinus {
  Expression operand = 1;
}

message GreaterThanOrEqual {
  Expression left = 1;
  Expression right = 2;
}

message Comparison {
  Expression left = 1;
  Expression right = 2;
  ComparisonOperator operator = 3;
}

enum ComparisonOperator {
  COMPARISON_OPERATOR_UNSPECIFIED = 0;
  COMPARISON_OPERATOR_EQUAL = 1;
  COMPARISON_OPERATOR_NOT_EQUAL = 2;
  COMPARISON_OPERATOR_LESS_THAN = 3;
  COMPARISON_OPERATOR_LESS_THAN_OR_EQUAL = 4;
  COMPARISON_OPERATOR_GREATER_THAN = 5;
  COMPARISON_OPERATOR_GREATER_THAN_OR_EQUAL = 6;
}

message Arithmetic {
  Expression left = 1;
  Expression right = 2;
  ArithmeticOperator operator = 3;
}

enum ArithmeticOperator {
  ARITHMETIC_OPERATOR_UNSPECIFIED = 0;
  ARITHMETIC_OPERATOR_ADD = 1;
  ARITHMETIC_OPERATOR_SUBTRACT = 2;
  ARITHMETIC_OPERATOR_MULTIPLY = 3;
}

message NullCheck {
  Expression operand = 1;
  bool negated = 2;
}

message BooleanBinary {
  Expression left = 1;
  Expression right = 2;
  BooleanOperator operator = 3;
}

enum BooleanOperator {
  BOOLEAN_OPERATOR_UNSPECIFIED = 0;
  BOOLEAN_OPERATOR_AND = 1;
  BOOLEAN_OPERATOR_OR = 2;
}

message BooleanNot {
  Expression operand = 1;
}

message InputReference {
  uint32 index = 1;
  LogicalType type = 2;
}

message Schema {
  repeated Field fields = 1;
}

message Field {
  string name = 1;
  LogicalType type = 2;
}

message LogicalType {
  bool nullable = 1;
  oneof type {
    EmptyType integer = 2;
    EmptyType bigint = 3;
    EmptyType boolean = 4;
    EmptyType varchar = 5;
    EmptyType tinyint = 6;
    EmptyType smallint = 7;
    EmptyType float = 8;
    EmptyType double = 9;
    EmptyType binary = 10;
    EmptyType date = 11;
    PrecisionType time = 12;
    PrecisionType timestamp = 13;
    PrecisionType timestamp_ltz = 14;
    DecimalType decimal = 15;
  }
}

message EmptyType {}

message PrecisionType {
  uint32 precision = 1;
}

message DecimalType {
  uint32 precision = 1;
  uint32 scale = 2;
}
