<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>tech.streamfusion</groupId>
        <artifactId>streamfusion-parent</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>streamfusion-native</artifactId>
    <packaging>pom</packaging>
    <name>StreamFusion : Native DataFusion Runtime</name>

    <build>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>${exec.maven.plugin.version}</version>
                <executions>
                    <execution>
                        <id>cargo-test</id>
                        <phase>test</phase>
                        <goals><goal>exec</goal></goals>
                        <configuration>
                            <executable>cargo</executable>
                            <arguments>
                                <argument>test</argument>
                                <argument>--locked</argument>
                            </arguments>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
