/*
 * Copyright 2026 StreamFusion Authors
 * Licensed under the Apache License, Version 2.0
 */
package tech.streamfusion.flink.deduplicate;

import static org.assertj.core.api.Assertions.assertThat;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Base64;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Queue;
import java.util.stream.Stream;
import org.apache.flink.core.memory.DataOutputSerializer;
import org.apache.flink.runtime.state.KeyGroupRangeAssignment;
import org.apache.flink.streaming.api.operators.KeyedProcessOperator;
import org.apache.flink.streaming.api.operators.OneInputStreamOperator;
import org.apache.flink.streaming.api.watermark.Watermark;
import org.apache.flink.streaming.runtime.streamrecord.StreamRecord;
import org.apache.flink.streaming.util.KeyedOneInputStreamOperatorTestHarness;
import org.apache.flink.table.catalog.ObjectIdentifier;
import org.apache.flink.table.data.DecimalData;
import org.apache.flink.table.data.GenericArrayData;
import org.apache.flink.table.data.GenericMapData;
import org.apache.flink.table.data.GenericRowData;
import org.apache.flink.table.data.RowData;
import org.apache.flink.table.data.StringData;
import org.apache.flink.table.data.TimestampData;
import org.apache.flink.table.planner.plan.utils.KeySelectorUtil;
import org.apache.flink.table.runtime.keyselector.RowDataKeySelector;
import org.apache.flink.table.runtime.operators.deduplicate.RowTimeDeduplicateFunction;
import org.apache.flink.table.runtime.typeutils.InternalTypeInfo;
import org.apache.flink.table.runtime.typeutils.RowDataSerializer;
import org.apache.flink.table.types.logical.ArrayType;
import org.apache.flink.table.types.logical.BigIntType;
import org.apache.flink.table.types.logical.BinaryType;
import org.apache.flink.table.types.logical.BooleanType;
import org.apache.flink.table.types.logical.CharType;
import org.apache.flink.table.types.logical.DateType;
import org.apache.flink.table.types.logical.DayTimeIntervalType;
import org.apache.flink.table.types.logical.DayTimeIntervalType.DayTimeResolution;
import org.apache.flink.table.types.logical.DecimalType;
import org.apache.flink.table.types.logical.DistinctType;
import org.apache.flink.table.types.logical.DoubleType;
import org.apache.flink.table.types.logical.FloatType;
import org.apache.flink.table.types.logical.IntType;
import org.apache.flink.table.types.logical.LocalZonedTimestampType;
import org.apache.flink.table.types.logical.LogicalType;
import org.apache.flink.table.types.logical.MapType;
import org.apache.flink.table.types.logical.MultisetType;
import org.apache.flink.table.types.logical.RowType;
import org.apache.flink.table.types.logical.SmallIntType;
import org.apache.flink.table.types.logical.StructuredType;
import org.apache.flink.table.types.logical.StructuredType.StructuredAttribute;
import org.apache.flink.table.types.logical.StructuredType.StructuredComparison;
import org.apache.flink.table.types.logical.TimeType;
import org.apache.flink.table.types.logical.TimestampKind;
import org.apache.flink.table.types.logical.TimestampType;
import org.apache.flink.table.types.logical.TinyIntType;
import org.apache.flink.table.types.logical.VarBinaryType;
import org.apache.flink.table.types.logical.VarCharType;
import org.apache.flink.table.types.logical.YearMonthIntervalType;
import org.apache.flink.table.types.logical.YearMonthIntervalType.YearMonthResolution;
import org.apache.flink.types.RowKind;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;

/** Generated byte-level parity for every key encoding accepted by the translator. */
public class StreamFusionDeduplicateKeyTypeParityTest {
    private static final int MAX_PARALLELISM = 128;
    private static final int ORDER_INDEX = 1;

    @ParameterizedTest(name = "{0}")
    @MethodSource("keyCases")
    void matchesFlinkForEverySupportedKey(String description, LogicalType keyType, Object key) throws Exception {
        RowType rowType = RowType.of(
                new LogicalType[] {keyType, new TimestampType(false, TimestampKind.ROWTIME, 3), new BigIntType(false)},
                new String[] {"dedup_key", "rowtime", "payload"});
        InternalTypeInfo<RowData> typeInfo = InternalTypeInfo.of(rowType);
        RowDataKeySelector nativeSelector = selector(typeInfo);
        RowDataKeySelector flinkSelector = selector(typeInfo);
        RowDataSerializer serializer = new RowDataSerializer(StreamFusionDeduplicateOperator.physicalRowType(rowType));

        try (KeyedOneInputStreamOperatorTestHarness<RowData, RowData, RowData> nativeHarness = harness(
                        new StreamFusionDeduplicateOperator(rowType, new int[] {0}, ORDER_INDEX, true),
                        nativeSelector,
                        typeInfo);
                KeyedOneInputStreamOperatorTestHarness<RowData, RowData, RowData> flinkHarness = harness(
                        new KeyedProcessOperator<>(
                                new RowTimeDeduplicateFunction(typeInfo, 0L, ORDER_INDEX, false, true, true)),
                        flinkSelector,
                        typeInfo)) {
            nativeHarness.open();
            flinkHarness.open();

            for (GenericRowData row : List.of(
                    row(key, 100, 1), row(key, 90, 2), row(key, 100, 3), row(null, 110, 4), row(null, 120, 5))) {
                nativeHarness.processElement(new StreamRecord<>(serializer.copy(row)));
                flinkHarness.processElement(
                        new StreamRecord<>(serializer.toBinaryRow(row).copy()));
            }
            nativeHarness.processWatermark(new Watermark(Long.MAX_VALUE));
            flinkHarness.processWatermark(new Watermark(Long.MAX_VALUE));

            assertThat(serializedOutput(nativeHarness, serializer))
                    .as(description)
                    .isEqualTo(serializedOutput(flinkHarness, serializer));
        }
    }

    @ParameterizedTest(name = "key-group: {0}")
    @MethodSource("keyCases")
    void assignsEverySupportedKeyToFlinksKeyGroup(String description, LogicalType keyType, Object key)
            throws Exception {
        RowType rowType = RowType.of(
                new LogicalType[] {keyType, new TimestampType(false, TimestampKind.ROWTIME, 3), new BigIntType(false)},
                new String[] {"dedup_key", "rowtime", "payload"});
        InternalTypeInfo<RowData> typeInfo = InternalTypeInfo.of(rowType);
        RowDataKeySelector selector = selector(typeInfo);
        GenericRowData input = row(key, 100, 1);
        int owner = KeyGroupRangeAssignment.assignKeyToParallelOperator(selector.getKey(input), MAX_PARALLELISM, 2);

        try (KeyedOneInputStreamOperatorTestHarness<RowData, RowData, RowData> harness = harness(
                new StreamFusionDeduplicateOperator(rowType, new int[] {0}, ORDER_INDEX, true),
                selector,
                typeInfo,
                2,
                owner)) {
            harness.open();
            harness.processElement(new StreamRecord<>(typeInfo.toRowSerializer().copy(input)));
            harness.endInput();
            assertThat(harness.getOutput()).as(description).hasSize(1);
        }
    }

    public static Stream<Arguments> keyCases() {
        return Stream.of(
                Arguments.of("BOOLEAN", new BooleanType(), true),
                Arguments.of("TINYINT", new TinyIntType(), (byte) -7),
                Arguments.of("SMALLINT", new SmallIntType(), (short) -700),
                Arguments.of("INTEGER", new IntType(), -70_000),
                Arguments.of("BIGINT", new BigIntType(), -7_000_000_000L),
                Arguments.of("FLOAT", new FloatType(), -1.25F),
                Arguments.of("DOUBLE", new DoubleType(), -1.25D),
                Arguments.of("CHAR", new CharType(5), StringData.fromString("abc")),
                Arguments.of("VARCHAR", new VarCharType(20), StringData.fromString("long-key-value")),
                Arguments.of("BINARY", new BinaryType(4), new byte[] {0, 1, -1, 4}),
                Arguments.of("VARBINARY", new VarBinaryType(20), new byte[] {9, 8, 7, 6, 5}),
                Arguments.of(
                        "DECIMAL compact",
                        new DecimalType(10, 2),
                        DecimalData.fromBigDecimal(new BigDecimal("-12345.67"), 10, 2)),
                Arguments.of(
                        "DECIMAL non-compact",
                        new DecimalType(25, 2),
                        DecimalData.fromBigDecimal(new BigDecimal("12345678901234567890123.45"), 25, 2)),
                Arguments.of("DATE", new DateType(), -10_000),
                Arguments.of("TIME", new TimeType(3), 45_678),
                Arguments.of("TIMESTAMP(3)", new TimestampType(3), TimestampData.fromEpochMillis(-1)),
                Arguments.of("TIMESTAMP(6)", new TimestampType(6), TimestampData.fromEpochMillis(-2, 999_000)),
                Arguments.of(
                        "TIMESTAMP_LTZ(6)", new LocalZonedTimestampType(6), TimestampData.fromEpochMillis(-2, 999_000)),
                Arguments.of(
                        "INTERVAL YEAR TO MONTH", new YearMonthIntervalType(YearMonthResolution.YEAR_TO_MONTH), -25),
                Arguments.of(
                        "INTERVAL DAY TO SECOND",
                        new DayTimeIntervalType(DayTimeResolution.DAY_TO_SECOND),
                        -90_061_007L),
                Arguments.of(
                        "DISTINCT INTEGER",
                        DistinctType.newBuilder(
                                        ObjectIdentifier.of("streamfusion", "test", "distinct_integer"), new IntType())
                                .build(),
                        -70_000),
                Arguments.of(
                        "STRUCTURED",
                        StructuredType.newBuilder(ObjectIdentifier.of("streamfusion", "test", "structured_key"))
                                .attributes(List.of(
                                        new StructuredAttribute("id", new BigIntType()),
                                        new StructuredAttribute("name", new VarCharType(20))))
                                .comparison(StructuredComparison.EQUALS)
                                .build(),
                        GenericRowData.of(42L, StringData.fromString("nested"))),
                Arguments.of("ARRAY", new ArrayType(new IntType()), new GenericArrayData(new Object[] {1, null, -2})),
                Arguments.of("MAP", mapType(), mapValue()),
                Arguments.of("MULTISET", new MultisetType(new VarCharType(false, 20)), multisetValue()),
                Arguments.of(
                        "ROW",
                        RowType.of(new BigIntType(), new VarCharType(20)),
                        GenericRowData.of(42L, StringData.fromString("nested"))));
    }

    private static MapType mapType() {
        return new MapType(new VarCharType(false, 20), new BigIntType());
    }

    private static GenericMapData mapValue() {
        LinkedHashMap<Object, Object> values = new LinkedHashMap<>();
        values.put(StringData.fromString("a"), 1L);
        values.put(StringData.fromString("b"), null);
        return new GenericMapData(values);
    }

    private static GenericMapData multisetValue() {
        LinkedHashMap<Object, Object> values = new LinkedHashMap<>();
        values.put(StringData.fromString("x"), 2);
        values.put(StringData.fromString("y"), 1);
        return new GenericMapData(values);
    }

    private static GenericRowData row(Object key, long timestamp, long payload) {
        GenericRowData row = new GenericRowData(RowKind.INSERT, 3);
        row.setField(0, key);
        row.setField(1, TimestampData.fromEpochMillis(timestamp));
        row.setField(2, payload);
        return row;
    }

    private static RowDataKeySelector selector(InternalTypeInfo<RowData> typeInfo) {
        return KeySelectorUtil.getRowDataSelector(
                StreamFusionDeduplicateKeyTypeParityTest.class.getClassLoader(), new int[] {0}, typeInfo);
    }

    private static KeyedOneInputStreamOperatorTestHarness<RowData, RowData, RowData> harness(
            OneInputStreamOperator<RowData, RowData> operator,
            RowDataKeySelector selector,
            InternalTypeInfo<RowData> typeInfo)
            throws Exception {
        return harness(operator, selector, typeInfo, 1, 0);
    }

    private static KeyedOneInputStreamOperatorTestHarness<RowData, RowData, RowData> harness(
            OneInputStreamOperator<RowData, RowData> operator,
            RowDataKeySelector selector,
            InternalTypeInfo<RowData> typeInfo,
            int parallelism,
            int subtask)
            throws Exception {
        KeyedOneInputStreamOperatorTestHarness<RowData, RowData, RowData> harness =
                new KeyedOneInputStreamOperatorTestHarness<>(
                        operator, selector, selector.getProducedType(), MAX_PARALLELISM, parallelism, subtask);
        harness.setup(typeInfo.toSerializer());
        return harness;
    }

    private static List<String> serializedOutput(
            KeyedOneInputStreamOperatorTestHarness<RowData, RowData, RowData> harness, RowDataSerializer serializer)
            throws Exception {
        List<String> bytes = new ArrayList<>();
        Queue<Object> output = harness.getOutput();
        Object item;
        while ((item = output.poll()) != null) {
            if (item instanceof StreamRecord) {
                @SuppressWarnings("unchecked")
                StreamRecord<RowData> record = (StreamRecord<RowData>) item;
                DataOutputSerializer target = new DataOutputSerializer(128);
                serializer.serialize(record.getValue(), target);
                bytes.add(Base64.getEncoder().encodeToString(target.getCopyOfBuffer()));
            }
        }
        return bytes;
    }
}
